version: "3"
services:
  mytodos:
    image: mytodos-frontend
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mytodos-network
  mytodos-server:
    image: mytodos-backend
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    networks:
      - mytodos-network
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mytodos-network
networks:
  mytodos-network:
    driver: bridge
volumes:
  mongo-data:
    driver: local